//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetShop.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspDanhMucHeThong
    {
        public long Id { get; set; }
        public Nullable<int> sap_xep { get; set; }
        public string ten_goi { get; set; }
        public string ghi_chu { get; set; }
        public string noi_dung { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public string phan_loai { get; set; }
        public Nullable<bool> is_lock { get; set; }
    }
}
