//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetShop.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspDetailUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspDetailUser()
        {
            this.AspStoreDocuments = new HashSet<AspStoreDocument>();
        }
    
        public long IdUser { get; set; }
        public string ho_ten { get; set; }
        public string UsersId { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string gioi_Tinh { get; set; }
        public string so_dien_thoai { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public string url_avatar { get; set; }
        public string name_avatar { get; set; }
        public string id_don_vi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspStoreDocument> AspStoreDocuments { get; set; }
    }
}
