//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetShop.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspHoSoCanBo
    {
        public long IdCanBo { get; set; }
        public string ho_ten { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string gioi_tinh { get; set; }
        public string so_dien_thoai { get; set; }
        public string url_avatar { get; set; }
        public string name_avatar { get; set; }
        public string email { get; set; }
        public string chuc_vu { get; set; }
    }
}
