//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetShop.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspStoreDocument
    {
        public long IdDocument { get; set; }
        public string NameDocument { get; set; }
        public string UrlDocument { get; set; }
        public Nullable<System.DateTime> DateNow { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<int> SumCount { get; set; }
        public string Note { get; set; }
        public Nullable<long> IdFoder { get; set; }
    
        public virtual AspDetailUser AspDetailUser { get; set; }
        public virtual AspFolder AspFolder { get; set; }
    }
}
