//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppNetShop.DomainModal
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Session
    {
        public string UserName { get; set; }
        public string ho_ten { get; set; }
        public string UsersId { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string gioi_Tinh { get; set; }
        public string so_dien_thoai { get; set; }
        public Nullable<bool> is_delete { get; set; }
        public string url_avatar { get; set; }
        public string name_avatar { get; set; }
        public string Email { get; set; }
        public string Id { get; set; }
        public long IdUser { get; set; }
    }
}
